###
# GET on LOCAL 
GET http://localhost:8080/cows
###
GET http://localhost:8080/cows/65c82ee102c055e047e7e308
###
# POST, PUT, and DELETE on LOCAL 
POST http://localhost:8080/cows
Content-Type: application/json

{
    "tag":"A5",
    "calfTag":"Z1",
    "color":"black",
    "birthday":"01-01-2015",
    "lostCalves": "1",
    "lateCalves": "1",
    "antibiotics": "0"        
}
###
PUT http://localhost:8080/cows/65c83ab848c135f41abd2448
Content-Type: application/json

{
    "tag":"A5",
    "calfTag":"Z1",
    "color":"black",
    "birthday":"01-01-2016",
    "lostCalves": "1",
    "lateCalves": "2",
    "antibiotics": "0"        
}
###
DELETE http://localhost:8080/cows/65c83ad948c135f41abd2449
###